package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EjecucionDeRunbookAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEjecucionDeRunbookAllPropertiesEquals(EjecucionDeRunbook expected, EjecucionDeRunbook actual) {
        assertEjecucionDeRunbookAutoGeneratedPropertiesEquals(expected, actual);
        assertEjecucionDeRunbookAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEjecucionDeRunbookAllUpdatablePropertiesEquals(EjecucionDeRunbook expected, EjecucionDeRunbook actual) {
        assertEjecucionDeRunbookUpdatableFieldsEquals(expected, actual);
        assertEjecucionDeRunbookUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEjecucionDeRunbookAutoGeneratedPropertiesEquals(EjecucionDeRunbook expected, EjecucionDeRunbook actual) {
        assertThat(actual)
            .as("Verify EjecucionDeRunbook auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEjecucionDeRunbookUpdatableFieldsEquals(EjecucionDeRunbook expected, EjecucionDeRunbook actual) {
        assertThat(actual)
            .as("Verify EjecucionDeRunbook relevant properties")
            .satisfies(a -> assertThat(a.getIniciadaEn()).as("check iniciadaEn").isEqualTo(expected.getIniciadaEn()))
            .satisfies(a -> assertThat(a.getFinalizadaEn()).as("check finalizadaEn").isEqualTo(expected.getFinalizadaEn()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getPasoActual()).as("check pasoActual").isEqualTo(expected.getPasoActual()))
            .satisfies(a -> assertThat(a.getMotivoFalla()).as("check motivoFalla").isEqualTo(expected.getMotivoFalla()))
            .satisfies(a -> assertThat(a.getNotas()).as("check notas").isEqualTo(expected.getNotas()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEjecucionDeRunbookUpdatableRelationshipsEquals(EjecucionDeRunbook expected, EjecucionDeRunbook actual) {
        assertThat(actual)
            .as("Verify EjecucionDeRunbook relationships")
            .satisfies(a -> assertThat(a.getRunbook()).as("check runbook").isEqualTo(expected.getRunbook()))
            .satisfies(a -> assertThat(a.getIncidente()).as("check incidente").isEqualTo(expected.getIncidente()));
    }
}
