package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PasoDeRunbookAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasoDeRunbookAllPropertiesEquals(PasoDeRunbook expected, PasoDeRunbook actual) {
        assertPasoDeRunbookAutoGeneratedPropertiesEquals(expected, actual);
        assertPasoDeRunbookAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasoDeRunbookAllUpdatablePropertiesEquals(PasoDeRunbook expected, PasoDeRunbook actual) {
        assertPasoDeRunbookUpdatableFieldsEquals(expected, actual);
        assertPasoDeRunbookUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasoDeRunbookAutoGeneratedPropertiesEquals(PasoDeRunbook expected, PasoDeRunbook actual) {
        assertThat(actual)
            .as("Verify PasoDeRunbook auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasoDeRunbookUpdatableFieldsEquals(PasoDeRunbook expected, PasoDeRunbook actual) {
        assertThat(actual)
            .as("Verify PasoDeRunbook relevant properties")
            .satisfies(a -> assertThat(a.getOrden()).as("check orden").isEqualTo(expected.getOrden()))
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getInstrucciones()).as("check instrucciones").isEqualTo(expected.getInstrucciones()))
            .satisfies(a -> assertThat(a.getObligatorio()).as("check obligatorio").isEqualTo(expected.getObligatorio()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPasoDeRunbookUpdatableRelationshipsEquals(PasoDeRunbook expected, PasoDeRunbook actual) {
        assertThat(actual)
            .as("Verify PasoDeRunbook relationships")
            .satisfies(a -> assertThat(a.getRunbook()).as("check runbook").isEqualTo(expected.getRunbook()));
    }
}
