package ar.edu.um.isa.oncall.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RunbookAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRunbookAllPropertiesEquals(Runbook expected, Runbook actual) {
        assertRunbookAutoGeneratedPropertiesEquals(expected, actual);
        assertRunbookAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRunbookAllUpdatablePropertiesEquals(Runbook expected, Runbook actual) {
        assertRunbookUpdatableFieldsEquals(expected, actual);
        assertRunbookUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRunbookAutoGeneratedPropertiesEquals(Runbook expected, Runbook actual) {
        assertThat(actual)
            .as("Verify Runbook auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRunbookUpdatableFieldsEquals(Runbook expected, Runbook actual) {
        assertThat(actual)
            .as("Verify Runbook relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getOrigenAlerta()).as("check origenAlerta").isEqualTo(expected.getOrigenAlerta()))
            .satisfies(a -> assertThat(a.getSeveridadMinima()).as("check severidadMinima").isEqualTo(expected.getSeveridadMinima()))
            .satisfies(a -> assertThat(a.getPatronFingerprint()).as("check patronFingerprint").isEqualTo(expected.getPatronFingerprint()))
            .satisfies(a -> assertThat(a.getTiempoMaxMinutos()).as("check tiempoMaxMinutos").isEqualTo(expected.getTiempoMaxMinutos()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRunbookUpdatableRelationshipsEquals(Runbook expected, Runbook actual) {
        assertThat(actual)
            .as("Verify Runbook relationships")
            .satisfies(a -> assertThat(a.getServicio()).as("check servicio").isEqualTo(expected.getServicio()));
    }
}
